{
 "title": "Agents",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "100ms",
 "templating": {
  "list": [
   {
    "name": "agentpos",
    "label": "Selected Agent",
    "query": "00, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10"
   },
   {
    "name": "vision_range",
    "label": "Visual Range",
    "query": "SELECT \"vision_range\" from \"simulation_params\""
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Velocity",
   "type": "timeseries",
   "description": "Showing agents' absolute velocity for all agents",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_data",
     "query": "SELECT mean(/velocity_agent-*/) FROM \"agent_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "orientation_agent-00" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Orientation",
   "type": "timeseries",
   "description": "Showing agents' orientation for all agents",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_data",
     "query": "SELECT mean(/orientation_agent-*/) FROM \"agent_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "orientation_agent-00" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Position",
   "type": "michaeldmoore-scatter-panel",
   "description": "Showing agents' position for a selected agent",
   "gridPos": { "h": 14, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_data",
     "query": "SELECT last(/pos._agent-${agentpos}/) FROM \"agent_data\" WHERE $timeFilter GROUP BY time(100ms) fill(null)",
     "select": [
      [
       { "params": [ "orientation_agent-00" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Decision Process",
   "type": "timeseries",
   "description": "Showing agents' decision variables",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_data",
     "query": "SELECT mean(/w_agent-${agentpos}/), mean(/u_agent-${agentpos}/) FROM \"agent_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "orientation_agent-00" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Depletion",
   "type": "timeseries",
   "description": "Depletion dynamics of individual resource patches over time",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "resource_data",
     "query": "SELECT mean(/resc_left*/) FROM \"resource_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "/resc_left*/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}