# Settings related to visualization and data reading/writing from/to the cobe environment
import os

# Read input generated by CoBe
ABM_WITH_COBE_INPUT = bool(int(os.getenv("ABM_WITH_COBE_INPUT", 0)))
ABM_COBE_INPUT_FOLDER = os.getenv("ABM_COBE_INPUT_FOLDER", "C:\\Users\\David\\Desktop\\ABM")
COBE_INPUT_FILENAME = os.getenv("COBE_INPUT_FILENAME", "cobe_input.json")
