# Settings related to visualization and data reading/writing from/to the cobe environment
import os

# Read input generated by CoBe
ABM_WITH_COBE_INPUT = bool(int(os.getenv("ABM_WITH_COBE_INPUT", 1)))
WITH_PMODULE = bool(int(os.getenv("WITH_PMODULE", 0)))

# Visualizing running PModule, no computation
PM_NUM_PREDATORS = int(os.getenv("PM_NUM_PREDATORS", 1))
ABM_COBE_INPUT_FOLDER_PM = os.getenv("ABM_COBE_INPUT_FOLDER_PM", "C:\\Users\\David\\Documents\\predprey_batches")
COBE_INPUT_FILENAME_PM = os.getenv("COBE_INPUT_FILENAMEPM", "out_pred.json")

# Input file for other behaviors such as abm
ABM_COBE_INPUT_FOLDER = os.getenv("ABM_COBE_INPUT_FOLDER", "C:\\Users\\David\\CoBe\\middleware")
COBE_INPUT_FILENAME = os.getenv("COBE_INPUT_FILENAME", "agent_list.json")
