behave_params_template = {
    "S_wu": 0,
    "T_w": 0.5,
    "Eps_w": 0,
    "g_w": 0.085,
    "B_w": 0,
    "w_max": 1,
    "Tau": 10,
    "S_uw": 0,
    "T_u": 0.5,
    "Eps_u": 3,
    "g_u": 0.085,
    "B_u": 0,
    "u_max": 1,
    "F_N": 2,
    "F_R": 1,
    "exp_vel_max": 3,
    "exp_stop_ratio": 0.15,
    "agent_radius": 10,
    "v_field_res": 1200,
    "pooling_time": 0,
    "pooling_prob": 0,
    "agent_consumption": 1,
    "vision_range": 2000,
    "agent_fov": 0.9,
    "evo_summary_path": None
}