"""parameters for interactive playground simulations"""

default_params = {
                "N": 5,
                "T": 100,
                "v_field_res": 1200,
                "width": 500,
                "height": 500,
                "framerate": 30,
                "window_pad": 30,
                "with_visualization": True,
                "show_vis_field": False,
                "show_vis_field_return": True,
                "pooling_time": 0,
                "pooling_prob":0,
                "agent_radius": 10,
                "N_resc": 10,
                "min_resc_perpatch": 200,
                "max_resc_perpatch": 201,
                "min_resc_quality": 0.25,
                "max_resc_quality": 0.25,
                "patch_radius": 45,
                "regenerate_patches": True,
                "agent_consumption": 1,
                "teleport_exploit": False,
                "vision_range": 500,
                "agent_fov": 0.5,
                "visual_exclusion": True,
                "show_vision_range": False,
                "use_ifdb_logging": False,
                "save_csv_files": False,
                "ghost_mode": True,
                "patchwise_exclusion": True,
                "parallel": False
}