name: Docker Image CI

on:
  pull_request:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          PROJECT: "cooperative_signaling"
        run: docker build . --file Dockerfile
